site_name: Målarkitektur
site_url: https://thomiz.github.io
nav:
    - Innledning: index.md
    - Arkitekturprinsipper: Arkitekturprinsipper.md
    - Målbilde: Overordnet-maalbilde.md
theme: readthedocs